# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20160105_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='client_ip_other',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
